### PR TITLE
Fix build for ROCm 5.7.0

### PR DESCRIPTION
**Pull request by jammm**
Seems to build locally now.

### CODE REVIEW

**Comment by jammm** [comment]
Made a draft because there's still an error during the final install for hipamd
```
CMake Error at hipamd/cmake_install.cmake:115 (file):
  file INSTALL cannot find
  "/opt/compiler-explorer/libs/rocm/5.7.0/bin/hipcc.bat": No such file or
  directory.
Call Stack (most recent call first):
  cmake_install.cmake:52 (include)
```

**Comment by jammm** [comment]
@mattgodbolt @partouf I was able to compile it successfully on my local machine.
image

Can we try this on the CI?

**Comment by jammm** [comment]
@mattgodbolt @partouf Just checking in. Can we try triggering a build ? It compiled for me locally.

**Comment by jammm** [comment]
@mattgodbolt @partouf ping! ^^

**Comment by jammm** [comment]
@mattgodbolt @partouf Checking in again. Can we trigger a build? :-)

**Comment by jammm** [comment]
Thanks for merging @partouf ! What's next ? Is there any way to test it?

**Comment by partouf** [comment]
I rebuilt the compiler, but we'll have to wait 30 minutes-ish before trying to build the library again. Will let you know how it turns out.

**Comment by partouf** [comment]
sorry i got confused, it didnt need compiler rebuilding, starting lib build now

**Comment by partouf** [comment]
build succeeded https://github.com/compiler-explorer/infra/actions/runs/6599061650/job/17927675248

**Comment by partouf** [comment]
library is now also installed, but I'm not sure how to use. Could you give it a try?

**Comment by jammm** [comment]
Looks good! Thanks!
https://godbolt.org/z/arjs5WbWT

**Pull request merged**
