### PR TITLE
Add build-dxc.sh for the DirectXShaderCompiler

### PR DESCRIPTION
**Pull request by jeremyong**
To test this script, I ran the image build and the script locally via Docker WSL2 and confirmed a successful build + archive.

### CODE REVIEW

**Comment by jeremyong** [comment]
This change is needed to support https://github.com/compiler-explorer/compiler-explorer/pull/3932

**Review by mattgodbolt — APPROVED** [review]
LGTM! Thanks. Will try with trunk shortly

**Comment by mattgodbolt** [comment]
First attempt at a build running at: https://github.com/compiler-explorer/infra/actions/runs/2822156822

**Comment by mattgodbolt** [comment]
it built! yay!

**Pull request merged**
