### PR TITLE
Add build for lfortran

### PR DESCRIPTION
**Pull request by mattgodbolt**
See https://github.com/compiler-explorer/compiler-explorer/pull/7119

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
Thank you very much!!

I was thinking to do the same.
I forgot about this, we have the following Dockerfile to test in the CI: https://github.com/lfortran/lfortran/blob/main/Dockerfile

**Comment by mattgodbolt** [comment]
Thanks @Thirumalai-Shaktivel -- yes I saw that Dockerfile and it was helpful in getting our own working! I'll look to get lfortan on the site today!

**Comment by mattgodbolt** [comment]
https://github.com/compiler-explorer/infra/actions/runs/12060642151 🎉

**Comment by Thirumalai-Shaktivel** [comment]
Nice, thank you!! 🎉

**Pull request merged**
