### PR TITLE
Update build script for rocm

### PR DESCRIPTION
**Pull request by yxsamliu**
Change github URL name to ROCm.

Get device libs, comgr and hipcc from llvm for ROCm 6.1 and above.

Make the script work for ROCm version above 5.7.

### CODE REVIEW

**Comment by yxsamliu** [comment]
depends on https://github.com/compiler-explorer/clang-builder/pull/64

**Review by mattgodbolt — APPROVED** [review]
Thanks! Seems reasonable to me

**Comment by yxsamliu** [comment]
Do you know whether /opt/compiler-explorer/libs/rocm/6.0.2 and /opt/compiler-explorer/libs/rocm/6.1.2 has been built and deployed to compiler-explorer? If so, do you have the link to the build log? It seems something may be wrong with /opt/compiler-explorer/libs/rocm/6.1.2 since device libs are missing.

**Comment by partouf** [comment]
This failed to build https://github.com/compiler-explorer/infra/actions/runs/9772880734/job/26978024514#step:6:1826
attempting a quick fix but gotta run soon

**Comment by partouf** [comment]
6.0.2 builds, installs and works on CE
6.1.2 builds, installs but does not work on CE

**Comment by yxsamliu** [comment]
> > 6.0.2 builds, installs and works on CE 6.1.2 builds, installs but does not work on CE
> 
> This should fix 6.1.2
> 
> #86
> 
> we need to rebuild 6.1.2 after that PR merged

also need this https://github.com/compiler-explorer/compiler-explorer/pull/6683 after 6.1.2 rebuilt

**Pull request merged**
