### PR TITLE
Update rocm build script for ROCm 5.7.0 support

### PR DESCRIPTION
**Pull request by jammm**
For https://github.com/compiler-explorer/compiler-explorer/pull/5569

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
Gonna trust you on this...I haven't really got time to look at this. cheers

**Comment by mattgodbolt** [comment]
Building at: https://github.com/compiler-explorer/infra/actions/runs/6449714629

**Comment by mattgodbolt** [comment]
Build failed:

```
 CMake Error at CMakeLists.txt:73 (find_package):
    Could not find a package configuration file provided by "AMDDeviceLibs"
    with any of the following names:
  
      AMDDeviceLibsConfig.cmake
      amddevicelibs-config.cmake
  
    Add the installation prefix of "AMDDeviceLibs" to CMAKE_PREFIX_PATH or set
    "AMDDeviceLibs_DIR" to a directory containing one of the above files.  If
    "AMDDeviceLibs" provides a separate development package or SDK, be sure it
    has been installed.
```

Did this build locally? The dockerfile is designed so you can test locally and be pretty sure it'll work.

**Comment by jammm** [comment]
> Build failed:
> 
> ```
>  CMake Error at CMakeLists.txt:73 (find_package):
>     Could not find a package configuration file provided by "AMDDeviceLibs"
>     with any of the following names:
>   
>       AMDDeviceLibsConfig.cmake
>       amddevicelibs-config.cmake
>   
>     Add the installation prefix of "AMDDeviceLibs" to CMAKE_PREFIX_PATH or set
>     "AMDDeviceLibs_DIR" to a directory containing one of the above files.  If
>     "AMDDeviceLibs" provides a separate development package or SDK, be sure it
>     has been installed.
> ```
> 
> Did this build locally? The dockerfile is designed so you can test locally and be pretty sure it'll work.

Sorry I'm quite new to this. I didn't build it locally as I didn't have access to a Linux machine over the weekend. My apologies. I'll fix this and make another PR?

**Comment by jammm** [comment]
@mattgodbolt @cgmb it seems like the current script is expecting a prebuilt `clang-rocm-5.7.0` to be available. That means I have to have llvm compiled with AMDGPU support right? What would the steps be to have those compiled and uploaded to aws? Should this be added to the build script? https://gist.github.com/cgmb/73086a32258934b1eb1f15340304ace6#file-ce-rocm-build-sh-L11-L23

**Comment by mattgodbolt** [comment]
we are already installing it on line 19, as best I understand it? our `ce_install install "clang-rocm ${VERSION}"` _ought_ to be installing but maybe it's wrong. In fact I think it might be failing due to the `"` quotes... but I'm not abel to check right now.

The `ce_install` is to install to `/opt/compiler-explorer` from our previously-built setups...and mayyybe this is because we hadn't yet build clang rocm 5.7.0? I haven't kept up with this.

**Comment by partouf** [comment]
So this actually PR https://github.com/compiler-explorer/infra/pull/1112/files lets install both Compiler and Library

These misc-builder changes are related to the Library, but the Compiler should then already exist.

Which is built by us "just" starting a build a special rocm version with clang-builder

So the order should be, build clang-rocm, then merge the PR in infra, then you can install clang, then you can build the library with this current PR, and then you can install the library.

I think in the future it would be helpful to make 2 separate infra PR's, 1 for the compiler, 1 for the library, so that we can also separate the steps.

I'll start the clang rocm build and keep you informed

**Comment by partouf** [comment]
Building here https://github.com/compiler-explorer/infra/actions/runs/6459872137/job/17536478564

**Comment by partouf** [comment]
Merged infra PR and
Building library again https://github.com/compiler-explorer/infra/actions/runs/6460490607/job/17538273039

**Comment by partouf** [comment]
The new clang is available,

However... the infra git clone is never updated here, so we still can't install the new clang here

**Comment by jammm** [comment]
I'll rebuild the docker locally and check on my side.

**Comment by partouf** [comment]
Finally building https://github.com/compiler-explorer/infra/actions/runs/6460490607/job/17539600700

**Comment by partouf** [comment]
Oh, but it has a bunch of fatal errors for some reason @jammm  https://github.com/compiler-explorer/infra/actions/runs/6460490607/job/17539600700#step:6:843

**Comment by cgmb** [comment]
It seems that ROCr is building with `-mcode-object-version=4` and there's a mismatch somewhere. Just a guess, but maybe the device libs were built with code object v5?

**Comment by jammm** [comment]
> It seems that ROCr is building with `-mcode-object-version=4` and there's a mismatch somewhere. Just a guess, but maybe the device libs were built with code object v5?

Yeah I was thinking the same. Wasn't there a code object change between ROCm 5.3 and 5.7 ?

**Comment by jammm** [comment]
> > It seems that ROCr is building with `-mcode-object-version=4` and there's a mismatch somewhere. Just a guess, but maybe the device libs were built with code object v5?
> 
> Yeah I was thinking the same. Wasn't there a code object change between ROCm 5.3 and 5.7 ?

I wonder if it's because of this change https://github.com/RadeonOpenCompute/llvm-project/commit/de3c2215ce5618df39e6150bfa53bda4ca0ee86f

**Comment by jammm** [comment]
Dumping the LLVM IR of `opencl.bc` I get `!1 = !{i32 1, !"amdgpu_code_object_version", i32 500}`
I suppose this means it's code object v5.

**Comment by jammm** [comment]
I'll send an email internally about this.

**Comment by jammm** [comment]
In the mean time, @partouf can we rebuild for clang-rocm-5.7.0 except with one of these changes:
1. This flag here `-mcode-object-version=4` from `4` to `5` https://github.com/RadeonOpenCompute/ROCR-Runtime/blob/master/src/image/blit_src/CMakeLists.txt#L70
2. from `none` to `5` https://github.com/RadeonOpenCompute/llvm-project/blob/amd-stg-open/amd/device-libs/cmake/OCL.cmake#L43

I suspect 1 is easier to do than 2 and I worry that doing 2 may introduce the same error to some other library that instead was linked for v5.

**Comment by partouf** [comment]
> In the mean time, @partouf can we rebuild for clang-rocm-5.7.0 except with one of these changes:
> 
> 1. This flag here `-mcode-object-version=4` from `4` to `5` https://github.com/RadeonOpenCompute/ROCR-Runtime/blob/master/src/image/blit_src/CMakeLists.txt#L70
> 2. from `none` to `5` https://github.com/RadeonOpenCompute/llvm-project/blob/amd-stg-open/amd/device-libs/cmake/OCL.cmake#L43
> 
> I suspect 1 is easier to do than 2 and I worry that doing 2 may introduce the same error to some other library that instead was linked for v5.

Not really.. the build script is here https://github.com/compiler-explorer/clang-builder/blob/main/build/build.sh#L118

if there were cmake variables that we could pass, sure

otherwise this has to be patched like we do here https://github.com/compiler-explorer/clang-builder/blob/main/build/build.sh#L282

**Comment by jammm** [comment]
Okay. I suppose the patch method would work for the time being. I am not sure if there will be a hotfix for 5.7.0, or perhaps we can simply wait for a fix in 5.7.x and then get to this.. either way is fine with me.

**Comment by jammm** [comment]
New PR was made at https://github.com/compiler-explorer/misc-builder/pull/70 and works fine now :-)

**Pull request merged**
